services:
  app:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8000:8000"
    environment:
      - DB_SERVER=mssql
      - DB_PORT=1433
      - DB_NAME=ImageGeneratorDB
      - DB_USER=sa
      - DB_PASSWORD=YourStrong@Password123
    depends_on:
      - mssql
    volumes:
      - .:/app
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Password123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      
volumes:
  mssql_data: